name: metia
description: "A new Flutter project,"

version: 1.1.02

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  provider: ^6.1.5
  win32_registry: ^1.0.3
  isar: 3.1.0+1
  isar_flutter_libs:
    git: 
      url: https://github.com/moaadhzair/isar_flutter_libs.git
  path_provider: ^2.1.5
  cached_network_image: any
  flutter_js: ^0.8.5  
  http: ^1.6.0
  webview_flutter: ^4.13.0
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  window_manager: ^0.2.7
  shared_preferences: ^2.2.2
  package_info_plus: ^9.0.0
  flutter_markdown: ^0.6.18
  supabase_flutter: ^2.12.0
  flutter_web_auth_2: ^5.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: 3.1.0+1
  build_runner: any


flutter:
  assets:
    - assets/icons/logo.svg
  uses-material-design: true
  
